### ISSUE TITLE
No working example

### ISSUE THREAD

**Issue by 6543** [StardustXR/atmosphere#1]
would be nice if the example provided would work and if the readme could state how to run that example

**Comment by 6543** [comment]
esp. since one of the files is a symlink ... to a destination that normaly should not exist for others ;)

**Comment by technobaboo** [comment]
just updated atmosphere fully to the new kdl format + switched the default to something that i use all the time in my demo videos, see if it fixes your issue!

**Comment by 6543** [comment]
![image](https://github.com/user-attachments/assets/506a9e1d-6d6b-4dcf-aadb-20f2f0543e66)

**Comment by technobaboo** [comment]
wow that's a failure on my part :p

**Comment by technobaboo** [comment]
try now

**Comment by 6543** [comment]
fixed with https://github.com/StardustXR/atmosphere/commit/0c8bfb91e8ca32a4895f858067334ed265517309 I would say
