### ISSUE TITLE
Document the config format of environments

### ISSUE THREAD

**Issue by 6543** [StardustXR/atmosphere#3]
atm you have to understand https://github.com/StardustXR/atmosphere/blob/dev/src/environment_data.rs and it's meanings

the current example is nice to test the program and get some clues about the config ... but If you want to start building your own one it's still -hardcore mode- with no docs & description at all

**Comment by technobaboo** [comment]
how did i do with the latest updates?

**Comment by 6543** [comment]
I would say 66c0ad1d60be9d541290e8efb12ae0452b9dd7ef fixes this :)

if new questions come up, I guess dedicated issues and changes to the code/examples/... are out of scope of this
